baseurl = "https://www.diapoesie-bijoux.com/"
title = "diapoesie bijoux"
theme = "hugo-theme-console"
languageCode = "en-us"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 

  [[params.navlinks]]
  name = "à propos/"
  url = "a-propos/"

  [[params.navlinks]]
  name = "boutique/"
  url = "https://diapoesie-bijoux.sumupstore.com/"
  
  [[params.navlinks]]
  name = "contact/"
  url = "contact/"
